# Generated by Django 4.2.2 on 2023-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
